### ISSUE TITLE
ModuleNotFoundError: No module named 'PyRoxy'

### ISSUE THREAD

**Issue by tahadouhi** [LSD00/Rave-parser#1]
![image](https://user-images.githubusercontent.com/10810222/193419888-2a2dd82e-4e4f-4bd1-8a8b-3c46eaada925.png)
![image](https://user-images.githubusercontent.com/10810222/193419909-6b2f9114-075d-4c7e-9ed2-5daed2d0da90.png)

ModuleNotFoundError: No module named 'PyRoxy'
cant run the script although I have installed all the requirements.

**Comment by LSD00** [comment]
Hello my dear friend, maybe you should try use: pip install git+https://github.com/MHProDev/PyRoxy.git , I will update it

**Comment by tahadouhi** [comment]
> Hello, I update req.txt, for usage : wget https://raw.githubusercontent.com/LSD00/Rave-parser/main/req.txt pip install -r req.txt

Great !
I really appreciate your help!
